#!/bin/bash

#---definitions
simtype=aamd-bilayer
step_monolayer=s1-build-lipidgrid
step_simulation=s4-sim
step_bilayer=s2-build-bilayer
step_equilibration=s3-equil
input_files=aamd-bilayer-equil

#---python scripts to build monolayer and bilayer
python -c "execfile('./amx/header');
MonolayerGrids(rootdir='s1-build-lipidgrid',structs_dir='sources/aamd-bilayer-lipids-structs');"
python -c "execfile('./amx/header');
Bilayer(rootdir='s2-build-bilayer',previous_dir='s1-build-lipidgrid');"

#---execute equilibration step
cd $step_equilibration
./script-equilibrate.pl
cd ..

#---execute simulation (continuation) step
cd $step_simulation
./script-sim.pl
cd ..
