#!/bin/bash

#---definitions
gpu_flag=gpu
step_monolayer=s01-build-lipidgrid
step_simulation=s04-sim
step_build=s02-build-bilayer
step_equilibration=s03-equil
input_files=cgmd-bilayer-equil

#---execute python step
python -c "execfile('./amx/header');
try: MonolayerGrids(rootdir='s01-build-lipidgrid');
except Exception,e:
	print str(e);
	traceback.print_exc();
	print 'fail';"
go=$(tail s01-build-lipidgrid/log-script-master)
if [[ "$go" =~ fail$ ]];then exit;fi

#---execute python step
python -c "execfile('./amx/header');
try: Bilayer(rootdir='s02-build-bilayer',previous_dir='s01-build-lipidgrid');
except Exception,e:
	print str(e);
	traceback.print_exc();
	print 'fail';"
go=$(tail s02-build-bilayer/log-script-master)
if [[ "$go" =~ fail$ ]];then exit;fi

#---execute equilibration step
cd $step_equilibration
echo "moved to "$step_equilibration", "$(pwd)
./script-equilibrate.pl
if [[ $(tail log-script-master) =~ fail$ ]];then exit;fi
cd ..

#---execute simulation (continuation) step
cd $step_simulation
./script-sim.pl
if [[ $(tail log-script-master) =~ fail$ ]];then exit;fi
cd ..

