#!/bin/bash

#---definitions
step_simulation=s03-sim
mdp_look_string=protein_construction_settings,aamd
step_build=s01-build-protein-water
gpu_flag=auto
specs_file=inputs\\/input_specs_protein.py
step_equilibration=s02-equil
input_files=aamd-protein-equil

#---execute python step
python -c "execfile('./amx/header');
try: ProteinWater(rootdir='$step_build');
except Exception,e:
	print str(e);
	traceback.print_exc();
	print 'fail';"
go=$(tail $step_build/log-script-master)
if [[ "$go" =~ fail$ ]];then exit;fi

#---execute equilibration step
cd $step_equilibration
echo "moved to "$step_equilibration", "$(pwd)
./script-equilibrate.pl
if [[ $(tail log-script-master) =~ fail$ ]];then exit;fi
cd ..

#---execute simulation (continuation) step
cd $step_simulation
./script-sim.pl
if [[ $(tail log-script-master) =~ fail$ ]];then exit;fi
cd ..

