#!/bin/bash

#---definitions
simtype=aamd-protein
step_simulation=s3-sim
step_build=s1-build-protein-water
input_files=aamd-protein-equil
step_equilibration=s2-equil

#---execute python step
python -c "execfile('./amx/header');
try: ProteinWater(rootdir='s1-build-protein-water');
except Exception,e:
	print str(e);
	traceback.print_exc();
	print 'fail';"
go=$(tail s1-build-protein-water/log-script-master)
if [[ "$go" =~ fail$ ]];then exit;fi

#---execute equilibration step
cd $step_equilibration
./script-equilibrate.pl
if [[ $(tail log-script-master) =~ fail$ ]];then exit;fi
cd ..

#---execute simulation (continuation) step
cd $step_simulation
./script-sim.pl
if [[ $(tail log-script-master) =~ fail$ ]];then exit;fi
cd ..

