#!/usr/bin/python

#---hostname-to-architecture dictionary
'''
The keys in valid_hostnames are single word strings excluding punctuation which can be mathced to the true
true hostname. For example, if $HOSTNAME is likely to be kraken.school.login2 then just use "kraken". This
dictionary also keeps track of the available architectures for each hostname.
'''
#---here the hostname is a single word excluding punctuation which can be matched to the true hostname
#---note that the first element in the corresponding list is the default architecture
valid_hostnames = {
	'compbio':['opterons_gpu','opterons','xeons'],
	}

#---header file definitions
#---note the variable naming must be cluster_header_hostname_architecture

cluster_header_compbio_opterons = \
"""#!/bin/bash
#PBS -l nodes=1:ppn=16,walltime=96:00:00
#PBS -j eo 
#PBS -q opterons
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
"""

cluster_header_compbio_xeons = \
"""#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=96:00:00
#PBS -j eo 
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
"""

cluster_header_compbio_opterons_scratch = [
"""#!/bin/bash
#PBS -l nodes=1:ppn=16,walltime=96:00:00
#PBS -j eo 
#PBS -q opterons
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
jobid=`echo $PBS_JOBID|cut -f1 -d '.'`     # get the id of the job
rundir="/scratch/job-$jobid"               # complete path to temp dir  
echo "Running on scratch in "$rundir       # report the directory
mkdir $rundir                              # make the tempdir  
cp -rv * $rundir                           # copy all files to tempdir
cd $rundir                                 # change to tempdir
""",
"""
mv -f * $PBS_O_WORKDIR                     # move all files to the home directory
cd /scratch                                # leave the directory
#rmdir $rundir                              # remove the directory if it is empty
exit
"""]

cluster_header_compbio_xeons_scratch = [
"""#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=96:00:00
#PBS -j eo 
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
jobid=`echo $PBS_JOBID|cut -f1 -d '.'`     # get the id of the job
rundir="/scratch/job-$jobid"               # complete path to temp dir  
echo "Running on scratch in "$rundir       # report the directory
mkdir $rundir                              # make the tempdir  
cp -rv * $rundir                           # copy all files to tempdir
cd $rundir                                 # change to tempdir
""",
"""
mv -f * $PBS_O_WORKDIR                     # move all files to the home directory
cd /scratch                                # leave the directory
rmdir $rundir                              # remove the directory if it is empty
exit
"""]

'''
HOW TO ADD CLUSTER SPECS
	1. Add the header string/list to script_repo
	2. Add default specifications to default_proc_specs
	3. Add the key you used in default_proc_specs to valid_hostnames with a regex-able HOSTNAME identifier
	4. Add the key and a suffix to gmx_suffixes if necesary
	4. Add the key and a suffix to gmx_overrides if necesary
'''

#---formalize the collection of scripts to avoid using globals
script_repo = {
	'cluster_header_compbio_opterons_gpu':cluster_header_compbio_opterons,
	'cluster_header_compbio_opterons':cluster_header_compbio_opterons,
	'cluster_header_compbio_opterons_scratch':cluster_header_compbio_opterons_scratch,
	'cluster_header_compbio_xeons':cluster_header_compbio_xeons,
	'cluster_header_compbio_xeons_scratch':cluster_header_compbio_xeons_scratch,
	}

#---default number of nodes, processors per node, and walltime
#---note the module item holds bash commands to set paths for gromacs utilities 
default_proc_specs = {
	'compbio_xeons':
		{'nnodes':4,'ppn':2,'walltime':48,
		'module':'module load gromacs-gcc',
		'scratch':False},
	'compbio_opterons':
		{'nodes':1,'ppn':16,'walltime':96,
		'module':'module load gromacs-gcc',
		'scratch':False},
	'compbio_opterons_gpu':
		{'nodes':1,'ppn':16,'walltime':96,
		'module':'module load gromacs-gcc-cuda',
		'scratch':False},
	}
	
#---gromacs paths
standard_gromacs_commands = [
	'mdrun','grompp','tpbconv','editconf','genbox','make_ndx','genion',
	'trjconv','gmxcheck','pdb2gmx',
	]

#---system-specific suffixes to the gromacs utilities
gmx_suffixes = {
	'compbio_xeons':'_mpi',
	'compbio_opterons':'_mpi',
	'compbio_opterons_gpu':'_mpi',
	}

#---system-specific commands to substitute for standard_gromacs_commands
#---note some commands require a number of processors NPROCS which is substituted by ./controller make
gmx_overrides = {
	'local':{'mdrun':'mdrun -nt 1',},
	'compbio_xeons':{'mdrun':'mpirun -np NPROCS mdrun_mpi',},
	'compbio_opterons':{'mdrun':'mpirun -np NPROCS mdrun_mpi',},
	}



