#!/usr/bin/python

#---CLUSTER HEADERS
#-------------------------------------------------------------------------------------------------------------

#---defaults for running the script locally
local_nprocs = 4
local_processor_type = ['standard','gpu'][0]

#---here the hostname is a single word excluding punctuation which can be matched to the true hostname
#---note that the first element in the corresponding list is the default architecture
valid_hostnames = {
	'compbio':['opterons','opterons_gpu','xeons'][0],
	'walnut':None,
	'tobias':None,
	'SEASNet':None,
	'kahlo':None,
	}

#---hostname-to-architecture dictionary
"""
The keys in valid_hostnames are single word strings excluding punctuation which can be mathced to the true
true hostname. For example, if $HOSTNAME is likely to be kraken.school.login2 then just use "kraken". This
dictionary also keeps track of the available architectures for each hostname.
"""

#---header file definitions
#---note the variable naming must be cluster_header_hostname_architecture

cluster_header_compbio_opterons = \
"""#!/bin/bash
#PBS -l nodes=1:ppn=16,walltime=96:00:00
#PBS -j eo 
#PBS -q opterons
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
"""

cluster_header_compbio_xeons = \
"""#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=96:00:00
#PBS -j eo 
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
"""

cluster_header_compbio_opterons_scratch = [
"""#!/bin/bash
#PBS -l nodes=1:ppn=16,walltime=96:00:00
#PBS -j eo 
#PBS -q opterons
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
jobid=`echo $PBS_JOBID|cut -f1 -d '.'`
rundir="/scratch/job-$jobid"
echo "Running on scratch in "$rundir
mkdir $rundir
cp -rv * $rundir
cd $rundir
""",
"""
mv -f * $PBS_O_WORKDIR
cd /scratch
rmdir $rundir
"""]

cluster_header_compbio_xeons_scratch = [
"""#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=96:00:00
#PBS -j eo 
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
jobid=`echo $PBS_JOBID|cut -f1 -d '.'`
rundir="/scratch/job-$jobid"
echo "Running on scratch in "$rundir
mkdir $rundir
cp -rv * $rundir
cd $rundir
""",
"""
mv -f * $PBS_O_WORKDIR
cd /scratch
rmdir $rundir
"""]

cluster_header_tobias = \
"""#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=24:00:00
#PBS -j eo
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
"""

cluster_header_SEASNet = \
"""#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=4:00:00
#PBS -j eo
#PBS -q batch
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
"""

cluster_header_kahlo = \
"""#!/bin/bash
#PBS -l nodes=1:ppn=4,walltime=24:00:00
#PBS -j eo
#PBS -q batch
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
"""

cluster_header_walnut = \
"""#!/bin/bash
#PBS -l nodes=1:ppn=32,walltime=24:00:00,pmem=1500mb
#PBS -j eo
#PBS -q long
#PBS -N gmxjob
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
"""

cluster_header_walnut_scratch = [
"""#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=24:00:00,pmem=1500mb
#PBS -j eo 
#PBS -N gmxjob
#PBS -q long 
echo "Job started on `hostname` at `date`"
cd $PBS_O_WORKDIR
function cleanup {
	cd /scratch-local
	cp -arv $rundir/* $PBS_O_WORKDIR/
	rm -rf $rundir
}
trap cleanup EXIT
jobid=`echo $PBS_JOBID|cut -f1 -d '.'`
rundir="/scratch-local/job-$jobid"
echo "Running on scratch in "$rundir
mkdir $rundir
rsync -avi --files-from=$PBS_O_WORKDIR/upload-rsync-list.txt ./ $rundir
cd $rundir
""",
"""
exit
"""]

#---formalize the collection of scripts to avoid using globals
script_repo = {
	'cluster_header_compbio_opterons_gpu':cluster_header_compbio_opterons,
	'cluster_header_compbio_opterons':cluster_header_compbio_opterons,
	'cluster_header_compbio_opterons_scratch':cluster_header_compbio_opterons_scratch,
	'cluster_header_compbio_xeons':cluster_header_compbio_xeons,
	'cluster_header_compbio_xeons_scratch':cluster_header_compbio_xeons_scratch,
	'cluster_header_tobias':cluster_header_tobias,
	'cluster_header_SEASNet':cluster_header_SEASNet,
	'cluster_header_kahlo':cluster_header_kahlo,
	'cluster_header_walnut':cluster_header_walnut,
	'cluster_header_walnut_scratch':cluster_header_walnut_scratch,
	}

"""
HOW TO ADD CLUSTER SPECS
	1. Add the header string/list to script_repo
	2. Add default specifications to default_proc_specs
	3. Add the key you used valid in_default_proc specs to_hostnames with a regex-able HOSTNAME identifier
	4. Add the key and a suffix to gmx_suffixes if necesary
	4. Add the key and a suffix to gmx_overrides if necesary
"""

#---FILE REGEXES
#-------------------------------------------------------------------------------------------------------------

#---regex list for files to remove
patlist = ['\.?\/?.+\.'+i+'$' for i in 
	['itp','top','mdp','tpr','xtc','trr','gro','edr','log','cpt','ndx',
		'dat','pdb','jpeg','jpg','pl','sh','png','ali','py','txt']]+\
	['^gmxpaths','^gmxcalls','^gmxjob','^cluster-','^\#.+\#$','^script-','^log-','^em-all-','^step-']
	
#---ignore reset delete candidates 
whitelist = ['^\.?\/?(docs|amx|sources/|inputs|controller)','^\.*\/*\.[^\/]','controller']

#---all folders are deleted only when empty except if they match the folder delete regex
folder_delete = ['^\.?\/?.+(homology)']

#---DOCUMENTATION
#-------------------------------------------------------------------------------------------------------------

#---documentation page
document_location = 'file://'+os.path.abspath(os.path.curdir)+'/docs/_build/html/index.html'

#---RUN SPECIFICATIONS
#-------------------------------------------------------------------------------------------------------------

#---default number of nodes, processors per node, and walltime
#---note the module item holds bash commands to set paths for gromacs utilities 
default_proc_specs = {
	'compbio_xeons':
		{'nnodes':4,'ppn':2,'walltime':48,
		'module':'module load gromacs-gcc',
		'scratch':False},
	'compbio_opterons':
		{'nodes':1,'ppn':16,'walltime':48,
		'module':'module load gromacs-gcc',
		'scratch':False},
	'compbio_opterons_gpu':
		{'nodes':1,'ppn':16,'walltime':48,
		'module':'module load gromacs-gcc-cuda',
		'scratch':False},
	'walnut':
		{'nodes':1,'ppn':32,'walltime':24,'pmem':'1500mb',
		'module':'module load gromacs/4.6.7-icc-single',
		'scratch':True},
	'tobias':
		{'nodes':1,'ppn':8,'walltime':24,'scratch':False,
		'module':'export PATH=$PATH:/usr/local/gromacs/bin/:/usr/local/bin/'},
	'SEASNet':
		{'nodes':1,'ppn':2,'walltime':4,'scratch':False,
		'module':'module load gromacs/gromacs-4.6.3'},
	'kahlo':
		{'nodes':1,'ppn':4,'walltime':24,'scratch':False,
		'module':'# no modules needed'},
	}
	
#---gromacs paths
standard_gromacs_commands = [
	'mdrun','grompp','tpbconv','editconf','genbox','make_ndx','genion',
	'trjconv','gmxcheck','pdb2gmx','genconf',
	]

#---system-specific suffixes to the gromacs utilities
gmx_suffixes = {
	'compbio_xeons':'_mpi',
	'compbio_opterons':'_mpi',
	'compbio_opterons_gpu':'_mpi',
	'walnut':'_mpi',
	}

#---system-specific commands to substitute for standard_gromacs_commands
#---note some commands require a number of processors NPROCS which is substituted by ./controller make
gmx_overrides = {
	'local':{
		'standard':{'mdrun':'mdrun -nt '+str(local_nprocs),},
		'gpu':{'mdrun':'mdrun -nb gpu_cpu -nt '+str(local_nprocs),},
		}[local_processor_type],
	'tobias':{'mdrun':'mdrun -nt 8',},
	'compbio_xeons':{'mdrun':'mpirun -np NPROCS mdrun_mpi',},
	'compbio_opterons':{'mdrun':'mpirun -np NPROCS mdrun_mpi',},
	'walnut':{'mdrun':'mpirun -np NPROCS mdrun_mpi',},
	'kahlo':{'mdrun':'mdrun':'mdrun -nt NPROCS'},
	}
	
#---convert gromacs 4 commands to gromacs 5
gmx_syntax5 = dict([(key,'gmx '+key) for key in standard_gromacs_commands])
special_keys5 = {'genbox':'gmx solvate','tpbconv':'gmx convert-tpr'}
for key in special_keys5: gmx_syntax5[key] = special_keys5[key]

#---paths to extra tools
#---set paths to DSSP executable and martinize.py for MARTINI protein simulations from scratch
tool_paths = {
	'dssp':'~/libs/dssp-2.0.4-linux-amd64',
	'martinize':'~/libs/martinize.py',
	'modeller':'mod9.15',
	'vmd':'vmd',
	}
	
#---DOCUMENTATION
#-------------------------------------------------------------------------------------------------------------

#---DOCUMENTATION
#-------------------------------------------------------------------------------------------------------------

helpstring = """\n
    Automacs (AMX) CONTROLLER.\n
    make script <simulation> : prepare a simulation and associated scripts 
                               see simulation types below for more details
    make script restart      : generates a CPT or GRO restart from an 
                               input-md-in.mdp in repo folder
    make upload              : prepare an upload list and rsync command for 
                               a continuation if the last step was "sim"
    make upload step=<dir>   : prepare an upload list for any step 
                               including the whole directory
    make rescript            : generate continue scripts for a simulation 
                               moved to a cluster  
    make clean               : reset the folder by deleting simulation data
                               note that the repo folder is exempt 
    make view cgmd <files>   : quick look at a CGMD simulation with GRO and 
                               XTC files in VMD using an ad hoc script
    make batch               : parameter sweep over simulations
    make docs <clean>        : generate docs if python-Sphinx is available
                               or remove them with clean

    simulations:
    -----------
    cgmd-bilayer         : coarse-grained bilayer under MARTINI force field
    aamd-protein         : protein in a water box using CHARMM27 force field    
    protein-homology     : structure prediction via MODELLER with either 
                           multiple templates or large batches of mutations
    cgmd-protein         : coarse-grained protein under MARTINI force field 
                           with assorted structure options via MARTINIZE
    restart              : generic restart which auto-detects CPT/GRO and
                           continues a simulation with repo/input-md-in.mdp

    *note that cgmd-protein, cgmd-protein-sculpt, aamd-bilayer, and multiply
    functions are under re-development and have been temporarily removed
    """

document_string = \
	"""
	Documentation is provided via python-Sphinx/sphinx-apidoc but is not 
	generally updated with each git push so you may	want to regenerate it.\n
	"""+str('file://'+os.path.abspath(os.path.curdir)+'/docs/_build/html/index.html')+"\n\n"

#---BASH SCRIPT CONSTANTS
#-------------------------------------------------------------------------------------------------------------

#---bash commands referenced in script_dict are recorded here
#---note that "preps" lists contain bash commands to copy general steps and connect the steps
#---note that "scripts" lists contain bash commands to run the steps in sequence

prepare_equil_sim = [
"""
#---copy equilibration files
if ! [ -d "$step_equilibration" ]; then cp -r ./sources/general-equil ./$step_equilibration
else cp -r ./sources/general-equil/* ./$step_equilibration;fi\n
#---connect equilibration settings to the previous step
sed -i 's/^SOURCEDIR.*/SOURCEDIR=\.\.\/'$step_build'/g' $step_equilibration/settings.sh
sed -i 's/^MDPLOOK.*/MDPLOOK='$mdp_look_string'/g' $step_equilibration/settings.sh
sed -i 's/^SPECSFILE.*/SPECSFILE='$specs_file'/g' $step_equilibration/settings.sh
sed -i 's/cp $AMXPATH\/.*/cp $AMXPATH\/'$input_files'\/\* \.\//g' $step_equilibration/settings.sh
""",
"""
#---copy simulation continuation files
if ! [ -d "$step_simulation" ]; then cp -r ./sources/general-sim ./$step_simulation
else cp -r ./sources/general-sim/* ./$step_simulation;fi\n
#---connect simulation settings to the previous step
sed -i 's/^SOURCEDIR.*/SOURCEDIR=\.\.\/'$step_equilibration'/g' $step_simulation/settings.sh
sed -i 's/^MDPLOOK.*/MDPLOOK='$mdp_look_string'/g' $step_simulation/settings.sh
sed -i 's/^SPECSFILE.*/SPECSFILE='$specs_file'/g' $step_simulation/settings.sh
sed -i 's/cp $AMXPATH\/.*/cp $AMXPATH\/'$input_files'\/\* \.\//g' $step_simulation/settings.sh
""",
]

prepare_restart = [
"""
#---copy simulation continuation files
mkdir ./$step_simulation
cp -r ./sources/general-sim-restart/* ./$step_simulation;
cp -r ./repo/* ./$step_simulation;
#---if detect_previous_step is set in the header then copy checkpoint files
#---...note that we use the prep scripts in a self-contained way, to avoid excessive python code
if ! [ -z "${detect_previous_step+xxx}" ]; then 
#---locate the latest checkpoint from the equilibrate folder
THISDIR=$(pwd)
cd $detect_previous_step
PRUN=0
for file in md.part*.cpt
do
	if [ $(echo ${file:7:4} | sed 's/^0*//') -gt $PRUN ]; then 
		PRUN=$(echo ${file:7:4} | sed 's/^0*//')
	fi
done
cd $THISDIR
#---copy checkpoint and input files
cp $detect_previous_step/$(printf md.part%04d.tpr $PRUN) ./$step_simulation/
cp $detect_previous_step/$(printf md.part%04d.cpt $PRUN) ./$step_simulation/
fi
"""
]

prepare_rescript = [
"""
sed -i 's/^STOPHOURS.*/STOPHOURS=\"'$walltime'\"/g' $detect_previous_step/settings.sh
"""
]

prepare_multiply = [
"""
#---copy simulation continuation files
mkdir ./$step_simulation
cp -r ./sources/general-sim-restart/* ./$step_simulation;
"""
]

call_equil = """#---execute equilibration step
cd $step_equilibration
echo "moved to "$step_equilibration", "$(pwd)
./script-equilibrate.pl
if [[ $(tail log-script-master) =~ fail$ ]];then exit;fi
cd ..
\n"""

call_sim = """#---execute simulation (continuation) step
cd $step_simulation
./script-sim.pl
if [[ $(tail log-script-master) =~ fail$ ]];then exit;fi
cd ..
\n"""

call_sim_restart = """#---execute simulation restart step
cd $step_simulation
./script-sim-restart.pl
./script-sim.pl
if [[ $(tail log-script-master) =~ fail$ ]];then exit;fi
cd ..
\n"""

call_sim_rescript = """#---execute simulation restart step
cd $detect_previous_step
./script-sim.pl
if [[ $(tail log-script-master) =~ fail$ ]];then exit;fi
cd ..
\n"""

call_sim_multiply = """#---execute simulation restart step
cd $step_simulation
./script-sim-restart.pl
if [[ $(tail log-script-master) =~ fail$ ]];then exit;fi
cd ..
\n"""

python_from_bash = """#---execute python step
python -c "execfile('./amx/header');
try: COMMAND;
except Exception,e:
	print str(e);
	traceback.print_exc();
	print 'fail';"
go=$(tail ROOTDIR/log-script-master)
if [[ "$go" =~ fail$ ]];then exit;fi
\n"""


#---BASH SCRIPT GENERATOR
#-------------------------------------------------------------------------------------------------------------

#---wrapper for regex substitutions below
def multiresub(switches,text):
	return re.compile("(%s)" % "|".join(map(re.escape,switches.keys()))).sub(
		lambda mo: switches[mo.string[mo.start():mo.end()]],text) 

#---amx procedure details
script_dict = {
	'cgmd-bilayer':{
		'prep':[prepare_equil_sim[0]+\
			"sed -i 's/STEPSTRING.*/STEPSTRING=\"npt\"/g' $step_equilibration/settings.sh"]+\
			prepare_equil_sim[1:],
		'steps':{
			'step_monolayer':'s01-build-lipidgrid',
			'step_build':'s02-build-bilayer',
			'step_equilibration':'s03-equil',
			'step_simulation':'s04-sim',
			'input_files':'cgmd-bilayer-equil',
			'gpu_flag':'gpu',
			'mdp_look_string':'bilayer_construction_settings,cgmd',
			'specs_file':r'inputs\\/input_specs_bilayer.py',
			},
		'continue':True,
		'sequence':[
			multiresub(dict({
				'ROOTDIR':'s01-build-lipidgrid',
				'COMMAND':'MonolayerGrids(rootdir=\'s01-build-lipidgrid\')',
				}),python_from_bash),
			multiresub(dict({
				'ROOTDIR':'s02-build-bilayer',
				'COMMAND':'Bilayer(rootdir=\'s02-build-bilayer\',previous_dir=\'s01-build-lipidgrid\')',
				}),python_from_bash),
			call_equil,
			call_sim,
			],
		},
	'cgmd-bilayer-sculpt':{
		'prep':[multiresub(dict({
			'general-equil':'flexible-equil',
			'general-sim':'flexible-sim',
			'equilibration':'equilibration_static'}),
			'\n'.join(prepare_equil_sim[:1]))]+\
			[multiresub(dict({
			'general-equil':'flexible-equil',
			'general-sim':'flexible-sim',
			'input_files':'input_files2',
			'step_build':'step_restrain'}),
			'\n'.join(prepare_equil_sim))],
		'steps':{
			'step_build':'s01-build-bilayer',
			'step_equilibration_static':'s02-equil',
			'step_equilibration':'s04-equil',
			'step_restrain':'s03-restrain',
			'step_simulation':'s05-sim',
			'input_files':'cgmd-bilayer-sculpt',
			'input_files2':'cgmd-bilayer-sculpt-equil',
			},
		'continue':True,
		'sequence':[
			multiresub(dict({
				'ROOTDIR':'s01-build-bilayer',
				'COMMAND':'BilayerSculpted(rootdir=\'s01-build-bilayer\')',
				}),python_from_bash),
			multiresub(dict({
				'step_equilibration':'step_equilibration_static'}),
				call_equil),
			multiresub(dict({
				'ROOTDIR':'s03-restrain',
				'COMMAND':'BilayerSculptedFixed(rootdir=\'s03-restrain\',previous_dir=\'s02-equil\')',
				}),python_from_bash),
			call_equil,
			call_sim,
			],
		},
	'aamd-bilayer':{
		'prep':prepare_equil_sim,
		'steps':{
			'step_monolayer':'s1-build-lipidgrid',
			'step_build':'s02-build-bilayer',
			'step_equilibration':'s03-equil',
			'step_simulation':'s04-sim',
			'input_files':'aamd-bilayer-equil',
			},
		'continue':True,
		'sequence':[
			multiresub(dict({
				'ROOTDIR':'s01-build-lipidgrid',
				'COMMAND':'MonolayerGrids(rootdir=\'s01-build-lipidgrid\')',
				}),python_from_bash),
			multiresub(dict({
				'ROOTDIR':'s02-build-bilayer',
				'COMMAND':'Bilayer(rootdir=\'s02-build-bilayer\',previous_dir=\'s01-build-lipidgrid\')',
				}),python_from_bash),
			call_equil,
			call_sim,
			],
		},
	'aamd-protein':{
		'prep':[prepare_equil_sim[0]+\
			"sed -i 's/STEPSTRING.*/STEPSTRING=\"nvt npt\"/g' $step_equilibration/settings.sh"]+\
			prepare_equil_sim[1:],
		'steps':{
			'step_build':'s01-build-protein-water',
			'step_equilibration':'s02-equil',
			'step_simulation':'s03-sim',
			'input_files':'aamd-protein-equil',
			'detect_previous_step':None,
			'mdp_look_string':'protein_construction_settings,aamd',
			'specs_file':r'inputs\\/input_specs_protein.py',
			},
		'continue':True,
		'sequence':[
			multiresub(dict({
				'ROOTDIR':'$step_build',
				'COMMAND':'ProteinWater(rootdir=\'$step_build\')',
				}),python_from_bash),
			call_equil,
			call_sim,		
			],
		},
	'cgmd-protein':{
		'prep':[prepare_equil_sim[0]+\
			"sed -i 's/STEPSTRING.*/STEPSTRING=\"nvt npt\"/g' $step_equilibration/settings.sh"]+\
			prepare_equil_sim[1:],
		'steps':{
			'step_build':'s01-build-protein-water',
			'step_equilibration':'s02-equil',
			'step_simulation':'s03-sim',
			'input_files':'cgmd-protein-equil',
			'mdp_look_string':'protein_construction_settings,cgmd',
			'specs_file':r'inputs\\/input_specs_protein.py',
			},
		'continue':True,
		'sequence':[
			multiresub(dict({
				'ROOTDIR':'s01-build-protein-water',
				'COMMAND':'ProteinWater(rootdir=\'$step_build\')',
				}),python_from_bash),
			call_equil,
			call_sim,		
			],
		},
	'protein-homology':{
		'prep':[],
		'steps':{
			'step_homology':'s01-homology',
			'input_files':'aamd-protein-homology',
			},
		'sequence':[
			multiresub(dict({
				'ROOTDIR':'s01-homology',
				'COMMAND':'ProteinHomology(rootdir=\'s01-homology\')',
				}),python_from_bash),
			'cd $step_homology;./script-best-models.py;cd ..',
			],
		},
	'restart':{
		'prep':prepare_restart+\
			["sed -i 's/use_gpu.*/use_gpu=\"gpu\"/g' $step_simulation/settings.sh"],
		'steps':{
			'step_simulation':'s01-restart',
			'detect_previous_step':None,
			'gpu_flag':'cpu',
			},
		'continue':True,
		'sequence':[
			call_sim_restart,
			],
		},
	'rescript':{
		'prep':prepare_rescript,
		'steps':{
			'detect_previous_step':None,
			'step_simulation':'s01-restart',
			'gpu_flag':'cpu',
			},
		'sequence':[
			call_sim_rescript,
			],
		},
	'multiply':{
		'prep':prepare_multiply,
		'steps':{
			'step_simulation':'s01-multiply',
			'detect_previous_step':None,
			},
		'continue':True,
		'sequence':[
			multiresub(dict({
				'ROOTDIR':'$step_simulation',
				'COMMAND':'Multiply(rootdir=\'$step_simulation\',previous_dir=\'$previus_step\','+\
					'nx=\'$nx\',ny=\'$ny\',nz=\'$nz\')',
				}),python_from_bash),
			call_sim_restart,
			call_sim,
			],
		},
	'cgmd-protein-bilayer':{
		'prep':[prepare_equil_sim[0]+\
			"sed -i 's/STEPSTRING.*/STEPSTRING=\"npt\"/g' $step_equilibration/settings.sh"]+\
			prepare_equil_sim[1:],
		'steps':{
			'step_build':'s01-protein-bilayer',
			'input_files':'cgmd-protein-bilayer',
			'step_equilibration':'s02-equil',
			'step_simulation':'s03-sim',
			},
		'sequence':[
			multiresub(dict({
				'ROOTDIR':'$step_build',
				'COMMAND':'ProteinBilayer(rootdir=\'$step_build\')',
				}),python_from_bash),
			call_equil,
			call_sim,
			],
		},
	}
