#!/usr/bin/python -B

mdpdefs = {
	#---MDP settings group for CGMD MARTINI simulations
	'cgmd':{
		#---defaults for redundant options (use None if only one)
		'defaults':{
			'potential':'verlet',
			'constrain':'none',
			'restrain':'none',
			'continue':'continue',
			'integrate':None,
			'output':None,
			'couple':None,
			},
		#---standard options
		'potential':{
			'original':{
				'cutoff-scheme':'group',
				'nstlist':10,
				'ns_type':'grid',
				'pbc':'xyz',
				'rlist':'1.2',
				'coulombtype':'Shift',
				'rcoulomb_switch':0.0,
				'rcoulomb':1.2,
				'vdw_type':'Shift',
				'rvdw_switch':0.9,
				'rvdw':1.2,
				'DispCorr':'No',
				},
			'verlet':{
				'cutoff-scheme':'verlet',
				'nstlist':10,
				'ns_type':'grid',
				'pbc':'xyz',
				'rlist':'1.2',
				'coulombtype':'cut-off',
				'rcoulomb':1.2,
				'vdw_type':'cut-off',
				'rvdw':1.2,
				'DispCorr':'No',
				},
			},
		'restrain':{
			'posre':{'define':'-DPOSRES'},
			'none':{},
			},			
		'constrain':{
			'none':{
				'constraints':'none',
				'constraint_algorithm':'Lincs',
				'lincs_order':4,
				'lincs_warnangle':30,
				},
			},
		'continue':{
			'continue':{'continuation':'yes'},
			'start':{'continuation':'no'},
			},
		'integrate':{
			'integrator':'md',
			'tinit':0.0,
			'dt':0.02,
			'nsteps':50000,
			'nstcomm':100,
			'comm-grps':'LIPIDS SOLV',
			'energygrps':'LIPIDS SOLV',
			},		
		'output':{
		 	'nstxout':10000,
			'nstvout':10000,
			'nstfout':0,
			'nstlog':2000,
			'nstenergy':2000,
			'nstxtcout':2000,
			'xtc_precision':100,
			},
		'couple':{
			'tcoupl':'Berendsen',
			'tc-grps':'LIPIDS SOLV',
			'tau_t':'1.0 1.0',
			'ref_t':'310 310',
			'Pcoupl':'Berendsen',
			'Pcoupltype':'semiisotropic',
			'tau_p':'2.0 2.0',
			'compressibility':'3e-4 3e-4',
			'ref_p':'1.0 1.0',
			},
		#---override for NPT bilayer and solvent
		'npt-bilayer':{
			'continue':'start',
			'integrate':{
				'integrator':'md',
				'tinit':0.0,
				'dt':0.01,
				'nsteps':100000,
				'nstcomm':100,
				'comm-grps':'LIPIDS SOLV',
				'energygrps':'LIPIDS SOLV',
				},		
			'output':{
			 	'nstxout':10000,
				'nstvout':10000,
				'nstfout':0,
				'nstlog':100,
				'nstenergy':100,
				'nstxtcout':100,
				'xtc_precision':100,
				},
			'couple':{
				'tcoupl':'Berendsen',
				'tc-grps':'LIPIDS SOLV',
				'tau_t':'1.0 1.0',
				'ref_t':'310 310',
				'Pcoupl':'Berendsen',
				'Pcoupltype':'semiisotropic',
				'tau_p':'1.0 1.0',
				'compressibility':'3e-4 3e-4',
				'ref_p':'1.0 1.0',
				},
			},
		#---override for minimization
		'minimize':{
			'couple':{
				'tcoupl':'no',
				'Pcoupl':'no',
				'gen_vel':'no',
				'gen_temp':310,
				'gen_seed':123,
				},
			'output':{
			 	'nstxout':500,
				'nstvout':500,
				'nstfout':0,
				'nstlog':500,
				'nstenergy':500,
				'nstxtcout':500,
				'xtc_precision':100,
				},
			'integrate':{
				'integrator':'steep',
				'tinit':0.0,
				'dt':0.01,
				'nsteps':100000,
				'nstcomm':1,
				'emtol':100,
				'emstep':0.01,
				},
			},		
		#---override for vacuum packing steps			
		'vacuum-packing':{
			'restrain':'posre',
			'integrate':{
				'integrator':'md',
				'tinit':0.0,
				'dt':0.01,
				'nsteps':500000,
				'nstcomm':10,
				},
			'couple':{
				'tcoupl':'Berendsen',
				'tc-grps':'SYSTEM',
				'tau_t':1.0,
				'ref_t':310,
				'Pcoupl':'Berendsen',
				'Pcoupltype':'semiisotropic',
				'tau_p':'0.5 0.5',
				'compressibility':'3e-5 0',
				'ref_p':'1.0 1.0',
				'gen_vel':'no',
				'gen_temp':310,
				'gen_seed':123123123,
				},
			},
		},		
	#---MDP settings group for CGMD MARTINI simulations of protein in solvent
	'cgmd-protein':{
		#---defaults for redundant options (use None if only one)
		'defaults':{
			'potential':'verlet',
			'constrain':'none',
			'restrain':'none',
			'continue':'continue',
			'integrate':None,
			'output':None,
			'couple':None,
			},
		#---standard options
		'potential':{
			'original':{
				'cutoff-scheme':'group',
				'nstlist':10,
				'ns_type':'grid',
				'pbc':'xyz',
				'rlist':'1.2',
				'coulombtype':'Shift',
				'rcoulomb_switch':0.0,
				'rcoulomb':1.2,
				'vdw_type':'Shift',
				'rvdw_switch':0.9,
				'rvdw':1.2,
				'DispCorr':'No',
				},
			'verlet':{
				'cutoff-scheme':'verlet',
				'nstlist':10,
				'ns_type':'grid',
				'pbc':'xyz',
				'rlist':'1.2',
				'coulombtype':'cut-off',
				'rcoulomb':1.2,
				'vdw_type':'cut-off',
				'rvdw':1.2,
				'DispCorr':'No',
				},
			},
		'restrain':{
			'posre':{'define':'-DPOSRES'},
			'none':{},
			},			
		'constrain':{
			'none':{
				'constraints':'none',
				'constraint_algorithm':'Lincs',
				'lincs_order':4,
				'lincs_warnangle':30,
				},
			},
		'continue':{
			'continue':{'continuation':'yes'},
			'start':{'continuation':'no'},
			},
		'integrate':{
			'integrator':'md',
			'tinit':0.0,
			'dt':0.02,
			'nsteps':50000,
			'energygrps':'Protein SOLV',
			},		
		'output':{
		 	'nstxout':10000,
			'nstvout':10000,
			'nstfout':0,
			'nstlog':2000,
			'nstenergy':2000,
			'nstxtcout':2000,
			'xtc_precision':100,
			},
		'couple':{
			'tcoupl':'Berendsen',
			'tc-grps':'Protein SOLV',
			'tau_t':'1.0 1.0',
			'ref_t':'310 310',
			'Pcoupl':'Berendsen',
			'Pcoupltype':'semiisotropic',
			'tau_p':'2.0 2.0',
			'compressibility':'3e-4 3e-4',
			'ref_p':'1.0 1.0',
			},
		#---override for NPT protein and solvent
		'npt':{
			'continue':'start',
			'integrate':{
				'integrator':'md',
				'tinit':0.0,
				'dt':0.01,
				'nsteps':100000,
				'energygrps':'Protein SOLV',
				},		
			'output':{
			 	'nstxout':10000,
				'nstvout':10000,
				'nstfout':0,
				'nstlog':100,
				'nstenergy':100,
				'nstxtcout':100,
				'xtc_precision':100,
				},
			'couple':{
				'tcoupl':'Berendsen',
				'tc-grps':'Protein SOLV',
				'tau_t':'1.0 1.0',
				'ref_t':'310 310',
				'Pcoupl':'Berendsen',
				'Pcoupltype':'semiisotropic',
				'tau_p':'1.0 1.0',
				'compressibility':'3e-4 3e-4',
				'ref_p':'1.0 1.0',
				},
			},
		#---override for NVT protein and solvent
		'nvt':{
			'continue':'start',
			'integrate':{
				'integrator':'md',
				'tinit':0.0,
				'dt':0.01,
				'nsteps':100000,
				'energygrps':'Protein SOLV',
				},		
			'output':{
			 	'nstxout':10000,
				'nstvout':10000,
				'nstfout':0,
				'nstlog':100,
				'nstenergy':100,
				'nstxtcout':100,
				'xtc_precision':100,
				},
			'couple':{
				'tcoupl':'Berendsen',
				'tc-grps':'Protein SOLV',
				'tau_t':'1.0 1.0',
				'ref_t':'310 310',
				'Pcoupl':'no',
				},
			},
		#---override for minimization
		'minimize':{
			'couple':{
				'tcoupl':'no',
				'Pcoupl':'no',
				'gen_vel':'no',
				'gen_temp':310,
				'gen_seed':123,
				},
			'output':{
			 	'nstxout':500,
				'nstvout':500,
				'nstfout':0,
				'nstlog':500,
				'nstenergy':500,
				'nstxtcout':500,
				'xtc_precision':100,
				},
			'integrate':{
				'integrator':'steep',
				'tinit':0.0,
				'dt':0.01,
				'nsteps':100000,
				'nstcomm':1,
				'emtol':100,
				'emstep':0.01,
				},
			},		
		},		
	#---MDP settings group for atomistic CHARMM simulations
	'aamd':{
		#---defaults for redundant options (use None if only one)
		'defaults':{
			'potential':'verlet',
			'continue':'continue',
			'couple':None,
			'integrate':None,
			'constrain':None,
			'output':None,
			},
		#---standard options
		'potential':{
			'original':{
				},
			'verlet':{
				'cutoff-scheme':'verlet',
				'nstlist':20,
				'ns_type':'grid',
				'coulombtype':'PME',
				'pme_order':4,
				'fourierspacing':0.1125,
				'rcoulomb':0.9,
				'rlist':0.9,
				'rvdw':0.9,
				'pbc':'xyz',
				'dispcorr':'EnerPres',
				},
			},
		'couple':{
			'tcoupl':'V-rescale',
			'tc_grps':'Protein Non-Protein',
			'tau_t':'0.1 0.1',
			'ref_t':'300 300',
			'pcoupl':'Parrinello-Rahman',
			'pcoupltype':'isotropic',
			'tau_p':2.0,
			'ref_p':1.0,
			'compressibility':'4.5e-5',
			},
		'constrain':{
			'constraints':'h-bonds',
			'constraint_algorithm':'lincs',
			},
		'continue':{
			'continue':{'continuation':'yes'},
			'start':{'continuation':'no'},
			},
		'output':{
			'nstxout':5000,
			'nstvout':5000,
			'nstlog':1000,
			'nstenergy':1000,
			'nstxtcout':1000,		
			},
		'integrate':{
			'integrator':'md',
			'tinit':0,
			'dt':0.002,
			'nsteps':50000,
			'nstcomm':100,
			'nstcalcenergy':100,
			'comm-grps':'Protein non-Protein',
			},
		#---override for minimization
		'minimize':{
			'integrate':{
				'integrator':'steep',
				'nsteps':50000,
				'nstcomm':1,
				'emtol':10.0,
				'emstep':0.01,
				},
			'couple':{},
			},
		#---override for NVT protein and solvent
		'nvt-protein':{
			'continue':'start',
			'output':{
				'nstxout':1000,
				'nstvout':1000,
				'nstlog':100,
				'nstenergy':100,
				'nstxtcout':500,		
				},		
			'couple':{
				'tcoupl':'V-rescale',
				'tau_t':'0.1 0.1',
				'tc_grps':'Protein Non-Protein',
				'ref_t':'300 300',
				'pcoupl':'no',
				},	
			'constrain':{
				'constraints':'all-bonds',
				'constraint_algorithm':'lincs',
				},
			'integrate':{
				'integrator':'md',
				'tinit':0,
				'dt':0.001,
				'nsteps':10000,
				'nstcomm':100,
				'nstcalcenergy':100,
				'comm-grps':'Protein non-Protein',
				},
			},
		#---override for NVT protein and solvent
		'nvt-protein-short':{
			'continue':'start',
			'output':{
				'nstxout':1000,
				'nstvout':1000,
				'nstlog':100,
				'nstenergy':100,
				'nstxtcout':500,		
				},		
			'couple':{
				'tcoupl':'V-rescale',
				'tc_grps':'Protein Non-Protein',
				'tau_t':'0.1 0.1',
				'ref_t':'300 300',
				'pcoupl':'no',
				},	
			'constrain':{
				'constraints':'all-bonds',
				'constraint_algorithm':'lincs',
				},
			'integrate':{
				'integrator':'md',
				'tinit':0,
				'dt':0.0001,
				'nsteps':10000,
				'nstcomm':100,
				'nstcalcenergy':100,
				'comm-grps':'Protein non-Protein',
				},
			},		
		#---override for NPT protein and solvent
		'npt-protein':{
			'continue':'start',
			'output':{
				'nstxout':1000,
				'nstvout':1000,
				'nstlog':100,
				'nstenergy':100,
				'nstxtcout':500,		
				},		
			'couple':{
				'tcoupl':'V-rescale',
				'tc_grps':'Protein Non-Protein',
				'tau_t':'0.1 0.1',
				'ref_t':'300 300',
				'pcoupl':'Berendsen',
				'pcoupltype':'isotropic',
				'tau_p':1.0,
				'ref_p':1.0,
				'compressibility':'4.5e-5',
				},	
			'constrain':{
				'constraints':'all-bonds',
				'constraint_algorithm':'lincs',
				},
			'integrate':{
				'integrator':'md',
				'tinit':0,
				'dt':0.001,
				'nsteps':10000,
				'nstcomm':100,
				'nstcalcenergy':100,
				'comm-grps':'Protein non-Protein',
				},
			},
		},
	}

