#!/usr/bin/python

#---if imports fail it is because you are running from automacs root directory
import sys,traceback
try:
	from amx.amxsim import *
	from amx.lipidgrid import MonolayerGrids
	from amx.bilayer import Bilayer
	from amx.protein import ProteinWater
	from amx.proteinhomology import ProteinHomology
	from amx.tools import *
	import sys,traceback
except:
	#---in case of legitimate error make sure the error message is printed
	traceback.print_exc()
	from lipidgrid import MonolayerGrids
	from bilayer import Bilayer
	from protein import ProteinWater
	from proteinhomology import ProteinHomology
	from tools import *

