#!/usr/bin/python

#---if imports fail it is because you are running from automacs root directory
import sys,traceback
try:
	from amx.amxsim import *
	from amx.lipidgrid import MonolayerGrids
	from amx.bilayer import Bilayer
	from amx.protein import ProteinWater
	from amx.tools import *
	import sys,traceback
except:
	#---? investigating errors with no messages
	traceback.print_exc()
	from amxsim import *
	from lipidgrid import MonolayerGrids
	from bilayer import Bilayer
	from protein import ProteinWater
	from tools import *

