#!/usr/bin/python

#---if imports fail it is because you are running from automacs root directory
import sys,traceback
#---disable pyc files
sys.dont_write_bytecode = True

try:

	from amx.amxsim import *
	from amx.lipidgrid import MonolayerGrids
	from amx.bilayer import Bilayer
	from amx.bilayer import BilayerSculpted
	from amx.bilayer import BilayerSculptedFixed
	from amx.protein import ProteinWater
	from amx.proteinbilayer import ProteinBilayer	
	from amx.proteinhomology import ProteinHomology
	from amx.simset import SimSet
	from amx.tools import *
	import sys,traceback

except:
	
	#---in case of legitimate error make sure the error message is printed
	traceback.print_exc()
	print 'importing locally'
	from amxsim import *
	from lipidgrid import MonolayerGrids
	from bilayer import Bilayer
	from bilayer import BilayerSculpted
	from amx.bilayer import BilayerSculptedFixed
	from protein import ProteinWater
	from proteinbilayer import ProteinBilayer
	from proteinhomology import ProteinHomology
	from simset import SimSet
	from tools import *

